apiVersion: v1
kind: Service
metadata:
  name: mywebping
  namespace: ping
  labels:
    app: mywebping
spec:
  selector:
    app: mywebping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebping-depl
  namespace: ping
  labels:
    app: mywebping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebping
  template:
    metadata:
      labels:
        app: mywebping
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: myrepo
        image: 678023591114.dkr.ecr.eu-west-1.amazonaws.com/myrepo
        ports:
        - containerPort: 80