kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: eks-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list","create","delete"]